name: FlowX Android CI & Upload

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FlowX repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build FlowX APK (Debug)
        run: ./gradlew assembleDebug

      - name: Generate version based on date-time
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Upload FlowX APK to API (OPEN, NO TOKEN)
        run: |
          echo "Uploading FlowX APK (version $VERSION)..."
          curl -v -X POST "https://api-box.pspware.dev/device-service/app/upload?version=${VERSION}" \
            -H 'accept: application/json' \
            -F 'file=@app/build/outputs/apk/debug/app-debug.apk;type=application/vnd.android.package-archive'

      - name: Save APK as GitHub Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: FlowX-APK-${{ env.VERSION }}
          path: app/build/outputs/apk/debug/app-debug.apk
